name: smarttek
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=2.1
  - matplotlib>=3.8
  - openpyxl>=3.1
  - pyarrow>=16.0
  - scikit-learn
  - numpy
  - pillow
  - pydicom
  - pip
  - pip:
      - PySide6>=6.5
      - pylibjpeg
      - pylibjpeg-libjpeg
      - pylibjpeg-openjpeg
